// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuv_-QE9c_Y4W2mzzxHRUgolty71AGvmk',
    appId: '1:1079698068207:web:97769e09611f24c96a411a',
    messagingSenderId: '1079698068207',
    projectId: 'cowork-e5788',
    authDomain: 'cowork-e5788.firebaseapp.com',
    storageBucket: 'cowork-e5788.firebasestorage.app',
    measurementId: 'G-Z4SX8HLBKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Q2ZqEEY1dOcxy2EF-_pD67BiWoQhi_A',
    appId: '1:1079698068207:android:0d7e488668d18d7c6a411a',
    messagingSenderId: '1079698068207',
    projectId: 'cowork-e5788',
    storageBucket: 'cowork-e5788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoCh9LPrhglekz5cpSquzpmjwY7T_ypZQ',
    appId: '1:1079698068207:ios:b39c73e92a388dbe6a411a',
    messagingSenderId: '1079698068207',
    projectId: 'cowork-e5788',
    storageBucket: 'cowork-e5788.firebasestorage.app',
    iosBundleId: 'com.example.cowork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoCh9LPrhglekz5cpSquzpmjwY7T_ypZQ',
    appId: '1:1079698068207:ios:b39c73e92a388dbe6a411a',
    messagingSenderId: '1079698068207',
    projectId: 'cowork-e5788',
    storageBucket: 'cowork-e5788.firebasestorage.app',
    iosBundleId: 'com.example.cowork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuv_-QE9c_Y4W2mzzxHRUgolty71AGvmk',
    appId: '1:1079698068207:web:22728ae09424cf1c6a411a',
    messagingSenderId: '1079698068207',
    projectId: 'cowork-e5788',
    authDomain: 'cowork-e5788.firebaseapp.com',
    storageBucket: 'cowork-e5788.firebasestorage.app',
    measurementId: 'G-S7234CQQYK',
  );
}
